apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secretpeeper
  namespace: default
subjects:
  - kind: ServiceAccount
    name: secret-peeper
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
