---
apiVersion: batch/v1
kind: Job
metadata:
  name: oathkeeper-secretgen
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: secret-keeper
      containers:
        - name: gen-secret
          image: registry.nearbycomputing.com/nbycomp/tools/oathkeeper
          command:
            - sh
            - -c
            - |
              if ! kubectl get secret {{ .Values.oathkeeper.secret.name }}; then
                kubectl create secret generic {{ .Values.oathkeeper.secret.name }} \
                  --from-literal=mutator.id_token.jwks.json="$(oathkeeper credentials generate --alg RS256)"
              else
                echo 'secret already exists'
              fi
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
