---
apiVersion: v1
kind: Pod
metadata:
  name: secret-fetchers
spec:
  containers:
    - name: fetch-secret
      image: bitnami/kubectl
      command:
        - sh
        - -c
        - |
          if ! kubectl get secret {{ .Values.nsoSecretName }}; then
            ssh-keygen -t rsa -b 4096 -f nso_id_rsa -N "" -C nso
            kubectl create secret generic {{ .Values.nsoSecretName }} \
              --from-file=privateKey=./nso_id_rsa \
              --from-file=publicKey=./nso_id_rsa.pub
          fi
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  serviceAccountName: secret-peeper
---
apiVersion: v1
kind: Secret
metadata:
  name: nso-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  topsecret: {{ "topsecretdontread" | b64enc }}

