---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchbase-backups
spec:
  resources:
    requests:
      storage: "100Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
