---
apiVersion: batch/v1
kind: Job
metadata:
  name: couchbase-init
  labels:
    name: couchbase-init
spec:
  template:
    spec:
      containers:
        - name: couchbase-init
          image: registry.nearbycomputing.com/nbycomp/core/registry/db-init:{{ .Values.global.versions.db_init }}
          env:
            - name: DB_HOST
              value: couchbase
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchbase-secret
                  key: password
            - name: DB_SERVICE_DEFS_BUCKET
              value: {{ .Values.bucketName }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "125m"
          volumeMounts:
            - mountPath: /opt/backups/
              name: couchbase-backups
      volumes:
        - name: couchbase-backups
          persistentVolumeClaim:
            claimName: couchbase-backups
      restartPolicy: OnFailure
