---
apiVersion: v1
kind: Secret
metadata:
  name: couchbase-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  # Try and lookup secret. On failure, generate them:
  {{- $fetched := (lookup "v1" "Secret" .Release.Namespace "couchbase-secret") | default (dict "data" dict) }}
  {{- $secret := (index $fetched.data "password") | default (randAlphaNum 24 | b64enc) }}
  password: {{ $secret | quote }}
