---
apiVersion: v1
kind: Service
metadata:
  name: couchbase
spec:
  selector:
    app: couchbase
  ports:
    - name: db01
      port: 8091
      targetPort: 8091
    - name: db02
      port: 8092
      targetPort: 8092
    - name: db03
      port: 8093
      targetPort: 8093
    - name: db04
      port: 8094
      targetPort: 8094
    - name: db05
      port: 11210
