apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  # fetch secret. If fail, create a new one and populate it:
  {{- $fetched := (lookup "v1" "Secret" .Release.Namespace "example-secret") | default (dict "data" dict)}}
  secretKey: {{ (index $fetched.data "secretKey") | default (randAlphaNum 32 | b64enc) }}
  {{- $pass := (index $fetched.data "adminKey") | default ( "randAlphaNum 32" | b64enc) }}
  adminKey: {{ $pass }}
  alertmanagerconf.yml: {{ (include "alertmanagerconfig" (dict "adminKey" $pass)) | toString | b64enc }}
  dsn: {{ (include "kratosDsnTpl" (dict "pass" $pass )) | b64enc }}
  config.yml: {{ (include "kratosConfTpl" (dict "cookieSecret" $pass "Values" .Values )) | toString | b64enc }}

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: dump-secret
      image: busybox
      command:
        - cat
        - /etc/prometheus/alertmanager.yml
      volumeMounts:
        - name: example-secret
          mountPath: /etc/prometheus/alertmanager.yml
          readOnly: true
          subPath: config.yml
  volumes:
    - name: example-secret
      secret:
        secretName: example-secret
