apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  # fetch secret. If fail, create an empty struct with data field
  {{- $fetched := (lookup "v1" "Secret" .Release.Namespace "example-secret") | default (dict "data" dict)}}
  # get field if exists. If not, generate one.
  {{- $akey := (index $fetched.data "adminKey") | default (randAlphaNum 32 | b64enc) }}
  adminKey: {{ $akey | b64enc }}
  {{- $skey := (index $fetched.data "secretKey") | default (randAlphaNum 32 | b64enc) }}
  secretKey: {{ $skey | b64enc }}
  {{- $amanconf := (.Files.Get "config/alertmanager.yml") }}
  alertmanagerConfig: {{ $amanconf | b64enc }}
